from snakemake.utils import min_version
min_version("7.12.1")
import glob
import os

config_path = config.get("config_path","config/config.yaml")
configfile: config_path
#configfile: "config/config.yaml"

EXTENSION = glob_wildcards(config["GENOMES"] + "/{samples}.{extension}").extension

if EXTENSION[0] == "gz":
	SAMPLES = glob_wildcards(config["GENOMES"] + "/{samples}.fa.{extension}").samples
else:
	SAMPLES = glob_wildcards(config["GENOMES"] + "/{samples}.{extension}").samples

num = config["GENE_COUNT"]
IDS = list(range(1,num+1))
mode = config.get("mode","accurate")
deep_mode = config.get("deep_mode","False")
MIN_ALIGN = config.get("MIN_ALIGN",4)

SELECTED_SAMPLES = []
od = {}
od_e = {}
section = None
if not os.path.exists("sampling_output.txt"):
	group_csv_arg = config.get("GROUP_CSV", "")
	if group_csv_arg and os.path.exists(group_csv_arg):
		os.system(f"python3 workflow/scripts/precompute_sampling.py --group_csv {group_csv_arg} {num} {config['GENOMES']}")
	else:
		os.system(f"python3 workflow/scripts/precompute_sampling.py {num} {config['GENOMES']}")

with open("sampling_output.txt") as f:
	for line in f:
		line = line.strip()
		if line.startswith("#"):
			section = line[1:].strip()  # Detect sections like "# SAMPLES"
		elif section == "SAMPLES":
			SAMPLES.append(line)
		elif section == "SELECTED_SAMPLES":
			SELECTED_SAMPLES.append(line)
		elif section == "od":
			key, value = line.split(",")
			od[key] = int(value)
		elif section == "od_e":
			key, value = line.split(",")
			od_e[key] = int(value)

if (mode == "fast"):
	include: "rules/mashtree.smk"
elif (mode == "balanced"):
	include: "rules/align.smk"
	include: "rules/sampling.smk"
	include: "rules/fasttree.smk"
else:
	include: "rules/sampling.smk"
	include: "rules/align.smk"
	include: "rules/tree.smk"
	
rule all:
	input:
		config["OUT_DIR"]+"/genetrees/gene_tree_merged.nwk"
